import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
// import {
//   NavigationMenu,
//   NavigationMenuContent,
//   NavigationMenuItem,
//   NavigationMenuLink,
//   NavigationMenuList,
//   NavigationMenuTrigger,
// } from "@/components/ui/navigation-menu";
import { AppSidebar } from "./components/sidebar/page";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import TopNavigationMenu from "./components/topnavigationmenu/page";

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// function TopNavigationMenu() {
//   return (
//     <nav className="hidden md:flex">
//       <NavigationMenu className="flex items-center">
//         <NavigationMenuList className="flex space-x-6">
//           <NavigationMenuItem>
//             <NavigationMenuTrigger>Your Experience</NavigationMenuTrigger>
//           </NavigationMenuItem>
//           <NavigationMenuItem>
//             <NavigationMenuTrigger>For Landlords</NavigationMenuTrigger>
//           </NavigationMenuItem>
//           <NavigationMenuItem>
//             <NavigationMenuTrigger>For Brokers</NavigationMenuTrigger>
//           </NavigationMenuItem>
//           <NavigationMenuItem>
//             <NavigationMenuTrigger>For Business</NavigationMenuTrigger>
//           </NavigationMenuItem>
//           <div className="h-8 bg-gray-300 w-[0.05rem]"></div>
//           <NavigationMenuItem>
//             <NavigationMenuTrigger>En</NavigationMenuTrigger>
//             <NavigationMenuContent className="absolute mt-2 bg-white shadow-lg z-10">
//               <NavigationMenuLink>English</NavigationMenuLink>
//               <NavigationMenuLink>French</NavigationMenuLink>
//             </NavigationMenuContent>
//           </NavigationMenuItem>
//           <NavigationMenuItem>
//             <NavigationMenuTrigger>Login</NavigationMenuTrigger>
//             <NavigationMenuContent className="absolute mt-2 bg-white shadow-lg z-10">
//               <NavigationMenuLink>Sign In</NavigationMenuLink>
//               <NavigationMenuLink>Register</NavigationMenuLink>
//             </NavigationMenuContent>
//           </NavigationMenuItem>
//         </NavigationMenuList>
//       </NavigationMenu>
//     </nav>
//   );
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 font-sans antialiased text-gray-900">
        {/* Header */}
        <header className="bg-white top-0 left-0 w-full z-50 shadow-md ">
          <div className="flex items-center justify-between max-w-screen-xl mx-auto">
            {/* Logo */}
            <a href="/pages/homepage">
              <div className="flex items-center space-x-4 ml-20">
                <img src="/assets/company-logo.png" alt="Company Logo" className="h-10" />
              </div>
            </a>
            {/* Navigation Menu (Large Screens) */}
            <TopNavigationMenu />
          </div>
        </header>

        {/* Main Content */}
        <SidebarProvider>
          <div className="flex">
            {/* Render the sidebar only on smaller screens */}
            <div className="">
              <AppSidebar />
            </div>
            {/* Toggle Sidebar Button*/}
            <div className="fixed top-4 left-4 z-50">
              <SidebarTrigger />
            </div>
            {/* Main content area */}
            <main className="flex-1 max-w-screen-xl mx-auto">{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}